name: ez_validator
description: Dead simple field/object schema validation for flutter,EzValidator api is inspired by Yup
version: 0.2.1
homepage: https://github.com/X-SLAYER/EzValidator
documentation: https://github.com/X-SLAYER/EzValidator#methods

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
